---
title: "R Notebook"
output: html_notebook
---
```{r}

library(readxl)
# w packages

#instalowanie pakietu 
#install --> zostawiamy domyslkne repozytorium --> wpisujemy w puste posle readxl --> intsall

```


```{r}
policja <- read.csv("../data_raw/policja-droga-info-dzienne.csv")

# dwie kropki to wejscie do folderu poziom wyzej
# używaj tabulatora aby znalezsc dany plik

#w wyniku otrzymujemy ramke danych

policja
```

```{r}
gospodarstwo <- read_xlsx("../data_raw/gospodarstwa.xlsx")


```

```{r}
class(policja)
ncol(policja)
nrow(policja)
dim(policja)
colnames(policja)
str(policja)
```
```{r}
policja[1:10,] #wyswietlkenie wszytskich kolumni pierwszych 10 wierszy
policja[,c(1,3)] 
policja[,c("data", "interwencje")]
policja[1:10, c("data", "interwencje")]
policja$interwencje[1:10]

```

```{r}
x <- c(2, 4, 6, 8)

x==4     #czy x jest rowny 4?
x!=4

x>4
x<=4

x==4 | x==8
# lub = |

x > 4 & x <8
# i = &


```

```{r}
x[c(1,3)]
x[c(TRUE, FALSE, TRUE, FALSE)]

x[x>4]
x[x>4 & x<=8]

```

```{r}
xy <- data.frame(x=1:4, y=5:8)
xy[3:4,]
xy[c(F, F, T, T),]
#y ma byc wiekszy niz

xy[xy$y>6,]

```
Ile  jest dni w których nie było zabitych w wypadkach?
```{r}
policja[policja$zabici_w_wypadkach==0, ]

45

```

Ile w zb policja w roku 2021, jest dni w ktoych nie bylo zabitych w wypadkach
```{r}
policja[policja$zabici_w_wypadkach== 0 & policja$rok==2021, ]
9

```

Jaka jest najmniejsza, najwięszka i średnia liczba interwencji w 2021 
```{r}

policja_2021 <- policja[policja$rok == 2021,]

min(policja_2021$interwencje) # to jest wektor

max(policja_2021$interwencje)

mean(policja_2021$interwencje)

```




